language: python
python:
  - '3.6'
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - make publish

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
